### ISSUE TITLE
API error: GET: http://127.0.0.1:7860/file=undefined

### ISSUE THREAD

**Issue by AssassinsLament** [nonnonstop/sd-webui-3d-open-pose-editor#28]
After updating the extension, I get this error:

API error: GET: http://127.0.0.1:7860/file=undefined {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'File at path D:\\DEVELOPMENT\\STABLEDIFFUSION\\stable-diffusion-webui\\undefined does not exist.'}
Traceback (most recent call last):
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\modules\api\api.py", line 145, in exception_handling
    return await call_next(request)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\modules\api\api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 338, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path D:\DEVELOPMENT\STABLEDIFFUSION\stable-diffusion-webui\undefined does not exist.

Stable Diffusion works normally and no errors if I disable this extension.

**Comment by nonnonstop** [comment]
Thank you for reporting.
Does the 3D Openpose tab work correctly? Is the 3D model displayed?

**Comment by AssassinsLament** [comment]
> Thank you for reporting. Does the 3D Openpose tab work correctly? Is the 3D model displayed?

The tab is there and seems to be working correctly, but there is no 3D model in the window.

**Comment by nonnonstop** [comment]
Try clearing your browser cache and reloading.

**Comment by AssassinsLament** [comment]
> Try clearing your browser cache and reloading.

I just did that and it worked and was about to comment you back! 

It definitely needed a few hard refreshes. For anyone having this issue, hold control and press f5.

Thank you sir!


![chrome_3T48ekx2Zt](https://user-images.githubusercontent.com/295773/228089799-f195bdb5-084e-4fee-b492-36fdacd43a47.png)

**Comment by nonnonstop** [comment]
Thank you.
I will fix the cache issue later.

**Comment by nonnonstop** [comment]
Fixed
