### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by po4920826** [nonnonstop/sd-webui-3d-open-pose-editor#57]
**Describe the bug**
3月30日安装的，4月12日更新后就无法使用了，找不到入口，之前可以从webUI的3d openpose标签进入，现在没了,controlnet没有问题

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: chrome firefox
 - A1111 WebUI Version: [22bcc7be428c94e9408f589966c2040187245d81]
 - Extension Version: [e0c50e19 (Wed Apr 12 13:21:43 2023)]
 - ControlNet Version: [e1885108 (Wed Apr 12 03:24:32 2023)]

**Additional context**

webUI启动时加载这个扩展报错

Error loading script: openpose_editor.py
Traceback (most recent call last):
  File "/home/diffusion/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/diffusion/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/diffusion/stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py", line 19, in <module>
    file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
TypeError: 'type' object is not subscriptable

**Comment by jkrauss82** [comment]
I have the same problem. Disclaimer: I am not a python pro. My suspicion: it is related to the python version, as this part of code might use a feature not supported by python 3.8 (which I am running)?

```
def get_asset_url(
    file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
) -> str:
...
```

Other environment variables match @po4920826's. What python version are you using?

**Comment by po4920826** [comment]
@jkrauss82
yes,it's 3.8.10 ,if this is the cause,I could just upgrade the python,thank you

**Comment by po4920826** [comment]
I had fixed it, I installed python 3.10.10 . extension is working now.

**Comment by jkrauss82** [comment]
Great, thanks for trying that out @po4920826, I will update my python as well then!

**Comment by ramonskie** [comment]
im not sure if this is the same issue
```
Launching Web UI with arguments: 
No module 'xformers'. Proceeding without it.
*** Error loading script: openpose_editor.py
    Traceback (most recent call last):
      File "/home/ramonskie/workspace/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/ramonskie/workspace/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/ramonskie/workspace/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py", line 19, in <module>
        file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
    TypeError: 'type' object is not subscriptable
```

running a111SD 1.4
python 3.10.11

**Comment by cangzihan** [comment]
把`stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py`文件里的：
```
def get_asset_url(
    file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
) -> str:
    if append is None:
        append = {"v": str(os.path.getmtime(file_path))}
    else:
        append = append.copy()
        append["v"] = str(os.path.getmtime(file_path))
    return f"/file={file_path.absolute()}?{urllib.parse.urlencode(append)}"
```
改成
```
def get_asset_url(file_path, append = None):
    if append is None:
        append = {"v": str(os.path.getmtime(file_path))}
    else:
        append = append.copy()
        append["v"] = str(os.path.getmtime(file_path))
    return f"/file={file_path.absolute()}?{urllib.parse.urlencode(append)}"
```
最后重启，虽然不是一个好的办法

**Comment by ramonskie** [comment]
@cangzihan this did work.
the question is now why does it work for everyone else and not me :)

**Comment by kmbarr** [comment]
I think this is being impacted by some changes made in Python 3.11 for typed dictionaries, but I wouldn't recommend updating Python beyond what the venv configuration in A1111 specifies [3.8.10].

Instead, I was able to get this working by relaxing the type hint on the optional dictionary a bit. This involves changing line 19 of `.../extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py`

FROM:
```
def get_asset_url(
    file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
) -> str:
```

TO:
```
def get_asset_url(
    file_path: pathlib.Path, append: typing.Optional[dict] = None
) -> str:
```

_s/o to @cangzihan for pointing me in the right direction, although removing the Optional entirely causes a different error._

**Comment by lOJQKA** [comment]
> 把`stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/scripts/openpose_editor.py`文件里的：
> 
> ```
> def get_asset_url(
>     file_path: pathlib.Path, append: typing.Optional[dict[str, str]] = None
> ) -> str:
>     if append is None:
>         append = {"v": str(os.path.getmtime(file_path))}
>     else:
>         append = append.copy()
>         append["v"] = str(os.path.getmtime(file_path))
>     return f"/file={file_path.absolute()}?{urllib.parse.urlencode(append)}"
> ```
> 
> 改成
> 
> ```
> def get_asset_url(file_path, append = None):
>     if append is None:
>         append = {"v": str(os.path.getmtime(file_path))}
>     else:
>         append = append.copy()
>         append["v"] = str(os.path.getmtime(file_path))
>     return f"/file={file_path.absolute()}?{urllib.parse.urlencode(append)}"
> ```
> 
> 最后重启，虽然不是一个好的办法

fixed. thank you.
