### ISSUE TITLE
[Bug] "Send to ControlNet" not working, "Control Model number" always empty

### ISSUE THREAD

**Issue by jangrewe** [nonnonstop/sd-webui-3d-open-pose-editor#96]
**Describe the bug**
After generating the pose images, i can not select any ControlNet number to send to. The dropdown menus all have the value "-".

**To Reproduce**
1. Go to 'Send to ControNet'
2. Click on dropdown for "Control Model number" to select an enabled ControlNet to send to

**Expected behavior**
The "Control Model number" shows the numbers of the enabled ControlNets

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - A1111 WebUI Version: 1.6.0
 - Extension Version: f2d5aac5 (Sat Apr 15 13:21:06 2023)
 - ControlNet Version: e67e0177 (Mon Sep 11 07:56:10 2023)

**Comment by AlfonGIT** [comment]
hello jangrewe, did you have any luck solving this issue? i have the very same problem 8(

**Comment by jangrewe** [comment]
Unfortunately not, i guess @nonnonstop will need to have a look at this 😔

**Comment by AlfonGIT** [comment]
sad... only warnings i get are from GradioDeprecation when loading controlnet, maybe there's a mismatch of versions of some libs or something... i'll try to debug it myself when i have some time. thanks for the response, appreciated!

**Comment by palentir** [comment]
I have the same issue, I wonder if any of the startup console messages are related, because I have newest php version and I had to fix some stuff. My startup params are: --skip-python-version-check --xformers --lowvram
Errors and warnings (May be unrelated):
 
C:\AI\Software\stable-diffusion-webui\venv\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
*** Error running process: C:\AI\Software\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\AI\Software\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\AI\Software\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "C:\AI\Software\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\AI\Software\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 696, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\AI\Software\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 608, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given
***   File "C:\AI\Software\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for DeepFaceLive - onnxruntime-gpu==1.12.1.
*** Command: "C:\AI\Software\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install onnxruntime-gpu==1.12.1 --prefer-binary
*** Error code: 1
*** stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12.1 (from versions: 1.15.0, 1.15.1, 1.16.0)
*** ERROR: No matching distribution found for onnxruntime-gpu==1.12.1

**Comment by ServeurpersoCom** [comment]
Same problem here

**Comment by Abishai2007** [comment]
This is not working for me either :(

**Comment by tritant** [comment]
Same problem here, no solution found?

**Comment by gohan2091** [comment]
Same here....

**Comment by lkw0711** [comment]
Same here

**Comment by grandfromages** [comment]
Same here...

**Comment by grandfromages** [comment]
I figured out how to fix this, and on my version - which I checked is up to date - it works exactly as expected. 
(probably not the cleanest fix, but... don't care, lol.)

Edit this file, as shown:  (you don't need to comment stuff out, I just did in case it didn't work so I could revert it easily.)
<img width="694" alt="3dOpenPose_Fix" src="https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/assets/113894706/4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b">

And showing it working: 
<img width="713" alt="3dOpenPose_Fix_1" src="https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/assets/113894706/567f25d9-ef14-4fc9-a795-d0f96e74645b">

Now, I'm off to play with 3d Openpose now that it works!

**Comment by yaan48** [comment]
It works!! Thank you

**Comment by gohan2091** [comment]
I cannot for the life of me get this working. The extension is totally broken for me. I have applied your file edit and now I have two 3D Open Pose menus in my interface and then when I generate the maps for the pose, I have a duplicate window below the first! Not only that but the "Control Model Number" dropdown box still doesn't show the control net number (the drop box only has the option of "-". The duplicate window below shows the 4 Control Net numbers but of course the upload image previews are all empty. Here is a screenshot to show:

![Screenshot 2023-11-26 234939](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/assets/127342824/dc0a64e8-88d9-4d7a-86a3-0e7663c522ff)

I am using SD.Next btw.

**Comment by GWNetwork** [comment]
> the 4 Control Net numbers

Looks like you've installed it twice? I would untick the plugin, then delete it from the extensions folder. Then make sure they are both gone after restarting. Then install it again, check if it works (as the dev may have already patched it), If not try his fix again.

**Comment by gohan2091** [comment]
> > the 4 Control Net numbers
> 
> Looks like you've installed it twice? I would untick the plugin, then delete it from the extensions folder. Then make sure they are both gone after restarting. Then install it again, check if it works (as the dev may have already patched it), If not try his fix again.

I only get it twice when I edit the .py file. When I restore the .py to original, I only have one copy. I have uninstalled the extension and reinstalled it but it has not helped. Also it's worth mentioning that This SD.Next installation is a new one (I re-did it 2 weeks ago) but prior to that with my old installation, I still had the issue.

**Comment by dsynclabsllc** [comment]
Using automatic11111, making the changes proposed above (regarding the mx_cnt var) did indeed fix it for me. This extension is a life saver so far. No more warped characters! I love it!

**Comment by StarCuto** [comment]
> 我想出了如何解决这个问题，在我的版本上 - 我检查了它是最新的 - 它完全按预期工作。 （可能不是最干净的修复，但是......不在乎，哈哈。
> 
> 编辑此文件，如下所示： （你不需要注释掉内容，我只是做了以防万一它不起作用，这样我就可以很容易地恢复它。 <img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGIxZThhMzAyMWUzZjk0NzY0ODVmMzZmNmM1Mjk3OTUzODhmYzExNWNiMGM0MWE1YWZiZDU4Y2EyYzMzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iFZGIq2qjUTP14u_-SWKbx5KlSaGzO2_f5TbQSIc_hg">
> 
> 并显示它的工作： <img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTBhMjNmNDZkYmRiYTk2M2I3ZGIxZTFjYmMyODZmNTAyN2Q2NjMwNWQwY2IyYzYxMjQzNmUyNzU1ZmI0NjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w-MeyUPzXJzZblg1VVwfT3oZcJkZMQpO9UJY-jYhGE8">
> 
> 现在，我可以开始玩 3d Openpose，因为它可以工作了！

2024/1/7 验证可行

**Comment by denissyd** [comment]
> > 我想出了如何解决这个问题，在我的版本上 - 我检查了它是最新的 - 它完全按预期工作。 （可能不是最干净的修复，但是......不在乎，哈哈。
> > 编辑此文件，如下所示： （你不需要注释掉内容，我只是做了以防万一它不起作用，这样我就可以很容易地恢复它。 <img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGIxZThhMzAyMWUzZjk0NzY0ODVmMzZmNmM1Mjk3OTUzODhmYzExNWNiMGM0MWE1YWZiZDU4Y2EyYzMzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iFZGIq2qjUTP14u_-SWKbx5KlSaGzO2_f5TbQSIc_hg">
> > 并显示它的工作： <img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTBhMjNmNDZkYmRiYTk2M2I3ZGIxZTFjYmMyODZmNTAyN2Q2NjMwNWQwY2IyYzYxMjQzNmUyNzU1ZmI0NjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w-MeyUPzXJzZblg1VVwfT3oZcJkZMQpO9UJY-jYhGE8">
> > 现在，我可以开始玩 3d Openpose，因为它可以工作了！
> 
> 2024/1/7 验证可行

你贴出来的图片消失了，能再发一下嘛？看你简介是东大的，我也是东大的，谢谢

**Comment by StarCuto** [comment]
您的邮件我已收到。      --交通学院  刘星坤

**Comment by AX30000** [comment]
> > > 我想如何解决这个问题，在我的版本上 - 我检查了它是最新的 - 它完全按预期工作。（可能不是最干净的修复，但是……无关，哈哈。编辑此文件，如下所示
> > > ： （你不需要注释掉内容，我只是做了万一它失效了，这样我就可以很容易地恢复它。
> > > 并显示它的工作：
> > > 现在，我可以开始玩 3d Openpose，因为它可以工作了！<img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGIxZThhMzAyMWUzZjk0NzY0ODVmMzZmNmM1Mjk3OTUzODhmYzExNWNiMGM0MWE1YWZiZDU4Y2EyYzMzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iFZGIq2qjUTP14u_-SWKbx5KlSaGzO2_f5TbQSIc_hg"><img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTBhMjNmNDZkYmRiYTk2M2I3ZGIxZTFjYmMyODZmNTAyN2Q2NjMwNWQwY2IyYzYxMjQzNmUyNzU1ZmI0NjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w-MeyUPzXJzZblg1VVwfT3oZcJkZMQpO9UJY-jYhGE8">
> > 
> > 
> > 2024/1/7 验证便携式
> 
> 你贴出来的图片消失了，能再发一下嘛？看你简介是东大的，我也是东大的，谢谢

解决问题了吗.教教我

**Comment by denissyd** [comment]
> > > > 我想如何解决这个问题，在我的版本上 - 我检查了它是最新的 - 它完全按预期工作。（可能不是最干净的修复，但是……无关，哈哈。编辑此文件，如下所示
> > > > ： （你不需要注释掉内容，我只是做了万一它失效了，这样我就可以很容易地恢复它。
> > > > 并显示它的工作：
> > > > 现在，我可以开始玩 3d Openpose，因为它可以工作了！<img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGIxZThhMzAyMWUzZjk0NzY0ODVmMzZmNmM1Mjk3OTUzODhmYzExNWNiMGM0MWE1YWZiZDU4Y2EyYzMzYzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iFZGIq2qjUTP14u_-SWKbx5KlSaGzO2_f5TbQSIc_hg"><img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDI0MDIsIm5iZiI6MTcwNDY0MjEwMiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTQxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTBhMjNmNDZkYmRiYTk2M2I3ZGIxZTFjYmMyODZmNTAyN2Q2NjMwNWQwY2IyYzYxMjQzNmUyNzU1ZmI0NjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w-MeyUPzXJzZblg1VVwfT3oZcJkZMQpO9UJY-jYhGE8">
> > > 
> > > 
> > > 2024/1/7 验证便携式
> > 
> > 
> > 你贴出来的图片消失了，能再发一下嘛？看你简介是东大的，我也是东大的，谢谢
> 
> 解决问题了吗.教教我

我也没解决。。。。

**Comment by Medivh0121** [comment]
> I figured out how to fix this, and on my version - which I checked is up to date - it works exactly as expected. (probably not the cleanest fix, but... don't care, lol.)
> 
> Edit this file, as shown: (you don't need to comment stuff out, I just did in case it didn't work so I could revert it easily.) <img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzExNjgsIm5iZiI6MTcwODczMDg2OCwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QyMzI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmFhNDRiMDQ1YzRiYjNmOTMyNzlhMDI4OTlhYzM5YmE2OTc1ZTE4M2FhNzkwNjJhZjUzMDdhNDFkMzYzZTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0zbSjLjq_6si_vcCNntFaTRGU93DMUZs-QMGSpJUxbU">
> 
> And showing it working: <img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzExNjgsIm5iZiI6MTcwODczMDg2OCwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QyMzI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjBiOThlMDJjYTA3ODQ0MzEzMzZiZGY4YTFmZjI1OGZiMDJkODNkYzFiYmVmOTNmNzlkNzAzMWQzZThmNGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oCGhWhFPkgSkcqNSI3DJt-riFTgLE7GLG-qka2YdHjM">
> 
> Now, I'm off to play with 3d Openpose now that it works!

Thanks! That works for me!

**Comment by newsoy** [comment]
> 你贴出来的图片消失了，能再发一下嘛？谢谢

**Comment by StarCuto** [comment]
您的邮件我已收到。      --交通学院  刘星坤

**Comment by acer5504** [comment]
> 我无论如何也弄不出来。这个扩展对我来说完全坏了。我已经应用了你的文件编辑，现在我的界面上有两个 3D Open Pose 菜单，然后当我为姿势生成地图时，第一个窗口下面有一个重复的窗口！不仅如此，“控制模型编号”下拉框仍然没有显示控制网络编号（下拉框只有“-”选项）。下面的重复窗口显示了 4 个控制网络编号，但当然上传图像预览都是空的。下面是一张截图：
> 
> ![截图 2023-11-26 234939](https://private-user-images.githubusercontent.com/127342824/285691104-dc0a64e8-88d9-4d7a-86a3-0e7663c522ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTc4MzUsIm5iZiI6MTcxODc5NzUzNSwicGF0aCI6Ii8xMjczNDI4MjQvMjg1NjkxMTA0LWRjMGE2NGU4LTg4ZDktNGQ3YS04NmEzLTBlNzY2M2M1MjJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMTQ1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdkM2Q3YzE0NmY5NTRmNjkwMTQ5Yzg0YjI2YWI0NGQ1ZTY0MTFmYzQ3YTk3Y2RiMmQzN2Y2ZDhmMTM1OTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FlifSeFXiNwcHWpRA8zPZzby7WtrEsw769TtoT6DG9E)
> 
> 顺便说一下，我正在使用 SD.Next。

me too

**Comment by StarCuto** [comment]
您的邮件我已收到。      --交通学院  刘星坤

**Comment by andoumusashi** [comment]
> I figured out how to fix this, and on my version - which I checked is up to date - it works exactly as expected. (probably not the cleanest fix, but... don't care, lol.)
> 
> Edit this file, as shown: (you don't need to comment stuff out, I just did in case it didn't work so I could revert it easily.) <img alt="3dOpenPose_Fix" width="694" src="https://private-user-images.githubusercontent.com/113894706/277461013-4f48c3eb-ebff-4879-b5ff-cc32fcbbf35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNDY0NzYsIm5iZiI6MTcyMTI0NjE3NiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMDEzLTRmNDhjM2ViLWViZmYtNDg3OS1iNWZmLWNjMzJmY2JiZjM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxOTU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTE4ZDE1ZGFhOTJkNzNkZDlkMWM3OGY5MWEzNjQyMTQ1MDc5NDMzMWVkZjU0NGZhMDYwMWRjZDJhM2I0YTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IIxPS3ELwY6E9u2gaaD96gCrEpo4KAbeFNdqiqpdM_o">
> 
> And showing it working: <img alt="3dOpenPose_Fix_1" width="713" src="https://private-user-images.githubusercontent.com/113894706/277461203-567f25d9-ef14-4fc9-a795-d0f96e74645b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNDY0NzYsIm5iZiI6MTcyMTI0NjE3NiwicGF0aCI6Ii8xMTM4OTQ3MDYvMjc3NDYxMjAzLTU2N2YyNWQ5LWVmMTQtNGZjOS1hNzk1LWQwZjk2ZTc0NjQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxOTU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2EzN2QyM2ZmM2EzMjI1YTRlM2NmZWVjM2ViZDFiNjE1MDFkNWMyYzYzZDQ3N2QxYzc3MTc4NjlkOTliYWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OBaPvxzGsYTMnLc5n8HG01NtWYzAVENi2BQRX4FD6oM">
> 
> Now, I'm off to play with 3d Openpose now that it works!

it's working! You are a genius!

**Comment by StarCuto** [comment]
您的邮件我已收到。      --交通学院  刘星坤

**Comment by sGasty** [comment]
Hi everyone!

I wanted to let you know that this issue has been resolved. You can find a simple and working solution at this https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/issues/115 . I have tested it myself, and it works.

**Comment by StarCuto** [comment]
您的邮件我已收到。      --交通学院  刘星坤
